### ISSUE TITLE
[Fabric 1.20.4] EMF & ETF Incompatibility 

### ISSUE THREAD

**Issue by Soufre** [Darkhax-Minecraft/Runelic#16] opened 2024-01-18 07:40 UTC
When using the latest versions of both [EMF](https://modrinth.com/mod/entity-model-features) and [ETF](https://modrinth.com/mod/entitytexturefeatures), the banner patterns **_Rune 1 through 9_** appear invisible as shown below.

Invisible banner patterns in a loom.
![2024-01-17_21 58 45](https://github.com/Darkhax-Minecraft/Runelic/assets/96512010/dbe9f1f8-2848-4e81-83be-7de3dd4a5252)

Invisible 'Rune 9' pattern on a banner block _while EMF & ETF are present._
![2024-01-17_21 59 01](https://github.com/Darkhax-Minecraft/Runelic/assets/96512010/e1a56c25-3241-42c2-aab4-e9f7d4edb85b)

The same 'Rune 9' banner pattern if both mods are removed.
![2024-01-17_22 45 33](https://github.com/Darkhax-Minecraft/Runelic/assets/96512010/1592a077-9514-4435-aa05-25c88ab58911)

Fabric API, Bookshelf, Runelic, EMF and ETF were the only mods used while verifying this issue.

**Comment by Darkhax** [comment] 2024-02-02 07:56
This mod is adding new banner patterns in the standard way and does not have any special rendering code that could mess up. I am guessing the issue is in EMF directly. I am closing this issue to centralize discussion on their issue tracker. If they do uncover some way this can be fixed on my end this issue report can be updated. https://github.com/Traben-0/Entity_Model_Features/issues/163

**Closed as completed by Darkhax** 2024-02-02 07:56 UTC
